config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :events
    resources :composers
    resources :composer_aliases
    resources :hyperlinks
    resources :pages
    resources :resources


    root to: "events#index"
  end

  root to: "date_selects#new"

  resources :events, only: [:index]
  resources :composers, only: [:index, :show]
  resources :hyperlinks, only: [:index]

  get 'pages/about'

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  resources :date_selects, only: [:new, :create]
  resources :resources, only: [:index]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events
end

app/models/composer.rb
class Composer < ActiveRecord::Base
  has_many :event_composer_connectors
  has_many :events, through: :event_composer_connectors
  has_many :composer_aliases


  validates :last_name, presence: true

  default_scope { order(last_name: :asc, first_name: :asc) }

  def first_letter_of_last_name
    last_name[0,1]
  end
end

app/models/composer_alias.rb
class ComposerAlias < ActiveRecord::Base
  belongs_to :composer
end

app/models/date_select.rb
class DateSelect 
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :date_range
  attr_accessor :start_month, :start_day, :start_year
  attr_accessor :end_month, :end_day, :end_year

  validates :start_month,
    presence: true

  validates :end_month,
    presence: true

  validates :start_day,
    presence: true

  validates :end_day,
    presence: true

  validates :start_year,
    presence: true, if: "date_range?"

  validates :end_year, 
    presence: true, if: "date_range?"

  def date_range?
    date_range == "1"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  include PgSearch

  validates :description, presence: true
  validates :date, presence: true
  validates :category_id, presence: true

  belongs_to :category
  has_many :event_composer_connectors
  has_many :composers, through: :event_composer_connectors

  before_save :remove_outer_paragraph_tag

  has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "none"
  do_not_validate_attachment_file_type :image

  def self.by_month(month)
    where('extract(month from date) = ?', month)
  end

  def self.by_day(day)
    where('extract(day from date) = ?', day)
  end

  scope :date_range, lambda {|start_date, end_date| where("date >= ? AND date <= ?", start_date, end_date )}

  pg_search_scope :search_description, :against => [:description]

  def remove_outer_paragraph_tag
    self.description = self.description.sub(/^\s*\<p\>/, '').sub(/\<\/p\>/, '')
  end
end

app/models/hyperlink.rb
class Hyperlink < ActiveRecord::Base
  validates :name, presence: true
  validates :url, presence: true

  belongs_to :link_category
end

app/models/link_category.rb
class LinkCategory < ActiveRecord::Base
  has_many :hyperlinks
end

app/models/message.rb
class Message
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :page_photos
end

app/models/page_photo.rb
class PagePhoto < ActiveRecord::Base
  belongs_to :page
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  validates :text, presence: true

  def sort_order
    text.downcase.gsub(/<[^>]*>/, '').gsub(/\"/, '')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_background_image
    images = [
      "01-background.png",
      "02-background.png",
      "03-background.png",
      "04-background.png",
      "05-background.png",
      "07-background.png",
      "08-background.png",
      "09-background.png",
      "10-background.png",
      "11-background.png",
      "12-background.png",
      "13-background.png",
      "14-background.png",
      "15-background.png",
      "16-background.png",
      "17-background.png",
      "18-background.png",
      "19-background.png",
      "20-background.png"
    ]

    image_num = rand(images.length)
    asset_path(images[image_num])
  end
end

app/helpers/common_helper.rb
module CommonHelper
  def copyright_year
    Time.now.year
  end
end

app/helpers/composers_helper.rb
module ComposersHelper
  def full_name(composer)
    if composer.first_name
      "#{composer.last_name}, #{composer.first_name}"
    else
      "#{composer.last_name}"
    end
  end

  def composer_link(composer)
    link_to full_name(composer), composer
  end

  def composer_columns(groups)
    [
      composer_column(groups, ('A'..'L')),
      composer_column(groups, ('M'..'Z'))
    ]
  end

  def composer_column(groups, range)
    column = {}
    range.each do |letter|
      column[letter] = groups[letter]
    end
    column
  end
end

app/helpers/date_select_helper.rb
module DateSelectHelper
  def month_options
    ['January', 'February', 'March', 'April', 'May', 'June',
     'July', 'August', 'September', 'October', 'November', 'December']
  end

  def day_options
    (1..31).to_a.map { |d| d.to_s }
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def todays_formatted_date_no_year
    formatted_date_no_year(Time.now)
  end

  def formatted_date_no_year(date)
    date.strftime("%B %-d")
  end

  def formatted_date(date)
    date.strftime("%B %-d, %Y")
  end

  def event_icon_for_category(name)
    case name
    when "birth"
      "birth-icon.png"
    when "death"
      "death-icon.png"
    when "performance"
      "performance-icon.png"
    else
      "event-icon.png"
    end
  end

  def event_page_title
    if search? 
      params[:search]
    elsif single_day?
      "#{formatted_date(Date.parse(start_date))}"
    elsif date_range? 
      "#{formatted_date(Date.parse(start_date))} &ndash; #{formatted_date(Date.parse(end_date))}"
    elsif params[:start_year]
      "#{params[:start_month]} #{params[:start_day]} in History"
    else
      "Today in History: #{todays_formatted_date_no_year}"
    end
  end

  def date_type_from_params
    if params[:search]
      :full_date
    elsif date_range?
      :full_date
    elsif single_day? 
      :no_date
    else
      :year_only
    end
  end

  def single_event_date(date, type)
    case type
    when :year_only 
      "#{date.year}: "
    when :full_date
      "#{formatted_date(date)}: "
    when :no_date
      ""
    else
      ""
    end
  end

  def sorted_by_date(events)
    events.sort_by { |event| event.date }
  end

  private
  def search?
    params[:search]
  end

  def single_day?
    params[:start_year] && (params[:start_year] != "") && (params[:date_range] == "0")
  end
  def date_range?
    params[:start_year] && (params[:start_year] != "") && (params[:date_range] == "1")
  end

  def start_date
    "#{params[:start_year]}-#{params[:start_month]}-#{params[:start_day]}"
  end

  def end_date
    "#{params[:end_year]}-#{params[:end_month]}-#{params[:end_day]}"
  end
end

app/helpers/hyperlinks_helper.rb
module HyperlinksHelper
  def sort_by_link_name(links)
   links.sort_by { |item| item.sort_by }
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/common/_footer.html.erb
<div class="footer">
  <div class="footer-separator">
    
     
    <div class="twit">
  <a href="https://twitter.com/musihist" class="twitter-follow-button" data-show-count="false">Follow @musihist</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
    
    
    <div class="back-to-top">
      <a href="#page_top"><i class="fa fa-caret-up" aria-hidden="true">&nbsp;</i>back to top</a>
    </div>
  </div>


  <div class="footer-body">
    <div class="footer-top-row">
      <div class="footer-title">
        Today in Music and History: <%= todays_formatted_date_no_year %>
      </div>
    </div>

    <div class="footer-event-body-text">
      <%= render partial: "common/footer_event", locals: {event: @random_event} %>
    </div>

    <div class="more-events-row">
      <%= button_to "more events", events_path, class: "more-events-button", method: "get"  %>
    </div>
 

  
  </div>
  <div class="copyright">&copy;<%= copyright_year %> Music and History</div>

</div>

app/views/common/_footer_event.html.erb
<div class="footer-random-event">
<span class="footer-todays-date-no-year"><%= event.date.year %>:</span>
<span class="footer-event-body-text"><%= event.description.html_safe %> </span>
</div>

app/views/common/_header.html.erb
<header>
  <a name="page_top"</a>

  <%= form_tag events_path, method: 'get', class: 'search-box' do %>
    <%= text_field_tag :search, "", placeholder: "   search", class: "search" %>
  <% end %>

  <div class="logo-row">
    <div class="page-logo">
      <%= link_to image_tag("logo.png"), root_path %>
    </div>

  </div>

  <div class="page-tagline">
    A CHRONOLOGICAL VIEW OF WESTERN MUSIC HISTORY IN THE CONTEXT OF WORLD EVENTS
  </div>


  <nav>
    <ul>
      <li><%= link_to "home", root_path %></li>
      <li><%= link_to "about", pages_about_path %></li>
      <li><%= link_to "composers", composers_path %></li>
      <li><%= link_to "links", hyperlinks_path %></li>
      <li><%= link_to "sources", resources_path %></li>
      <li><%= link_to "contact", contact_path %></li>
  </nav>
</header>